### ISSUE TITLE
dose not build on amazon VPS 

### ISSUE THREAD

**Issue by lostfile1** [faissaloo/ratmachine#11]
![builderror](https://user-images.githubusercontent.com/41842361/74113523-b566f580-4b72-11ea-8634-80d13aa1aeee.png)

**Comment by faissaloo** [comment]
`shards` is a Crystal command, your VPS seems to be running Ubuntu so you can use the following guide to install it: https://crystal-lang.org/install/on_ubuntu/

**Comment by lostfile1** [comment]
But i could have sworn i installed it

**Comment by lostfile1** [comment]
I coulda sworn I already did that meh i will close it

**Comment by faissaloo** [comment]
You might just have not added the install to your PATH
