### ISSUE TITLE
"make config" fails and captchas don't load

### ISSUE THREAD

**Issue by vnine99** [faissaloo/ratmachine#6]
doing "make config" gives me the following error
`amber encrypt production`
`Environment file not found for ./config/environments/production`
`Makefile:9: recipe for target 'config' failed`
`make: *** [config] Error 1`

Everything else seems to work fine except it can't posts because captchas don't load, it's just a small icon indicating that it's not loading.
![defrgthyjk](https://user-images.githubusercontent.com/54113195/72367512-96547f80-36fc-11ea-9da9-9356c169f74a.PNG)

This is probably an issue on my side and I might be missing something obvious because I'm pretty stupid.
Any help is appreciated ;D

**Comment by vnine99** [comment]
The production is is fixed (turns out i just had to make the file)
the captcha thing is still broken no matter how many times I redownload the repo tho :(

**Comment by faissaloo** [comment]
Sorry I didn't spot this earlier, atm in order for CAPTCHAs to work you need to:
1. Install ImageMagick  
2. From the root of the cloned repo run `mkdir -p public/dist/images/captcha`

**Comment by faissaloo** [comment]
You no longer have to create the directory, Ratmachine now automatically handles that. You will still need to install ImageMagick though.

**Comment by vnine99** [comment]
thank you very much! keep making cool stuff
