### ISSUE TITLE
cant build on docker

### ISSUE THREAD

**Issue by lostfile1** [faissaloo/ratmachine#8]
im using a raspberry pi and every time i use make dev it spits out this error
![Untitled](https://user-images.githubusercontent.com/41842361/74093036-8e3cf500-4a9a-11ea-9f47-a6236357c8f4.png)

**Comment by faissaloo** [comment]
The docker image is based on the official Amber Framework image which isn't built to run on ARM, if you want to build it you're going to have to install Crystal, Postgres and Amber manually then build Ratmachine with `make build`

**Comment by lostfile1** [comment]
I was able to install postges but crystal or amber is a nope but i guess i could take down my vps thats currently runnin a email server and try to build it on that

**Comment by faissaloo** [comment]
You might have to compile Crystal and Amber, idk how hard that is on the Pi but I think it's worth a shot.

**Comment by lostfile1** [comment]
oh its really hard its totally not worth it but so is having an email server on a vps i never use i shall hand over the link to it once im done working on it

**Comment by lostfile1** [comment]
im thinking about just taking the text board i already have down its using a script that is no longer maintained i have a revers nginx proxy pointed at it so i can use ssl with it

**Comment by lostfile1** [comment]
i think i can try doing this
http://public.portalier.com/raspbian/

**Comment by lostfile1** [comment]
I figured out how to install crystal and postgres
